trigger: none 

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Step 1: Install Terraform
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: 'latest'

  # Step 2: Azure CLI to authenticate with Azure
  - task: AzureCLI@2
    inputs:
      azureSubscription: '<YOUR_SERVICE_CONNECTION>'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az account show

  # Step 3: Checkout the code (Terraform and ARM template files)
  - checkout: self

  # Step 4: Terraform Init
  - script: terraform init
    displayName: 'Terraform Init'

  # Step 5: Terraform Plan
  - script: terraform plan -out=tfplan
    displayName: 'Terraform Plan'

  # Step 6: Terraform Apply
  - script: terraform apply -auto-approve tfplan
    displayName: 'Terraform Apply'
